### ISSUE TITLE
Subathon timer

### ISSUE THREAD

**Issue by Sdyess** [Sdyess/EsfandUpdates#7]
- [ ] Add feature toggle to enable/disable subathon timer
- [ ] Show remaining subathon time when feature is enabled?

**Comment by Mahcks** [comment]
Endpoint for subathon date - https://api.retpaladinbot.com/subathon/countdown

**Comment by Sdyess** [comment]
@Mahcks I meant the timer from when the subathon actually starts and shows remaining time :) You're the only person that might have access to that

**Comment by Mahcks** [comment]
@Sdyess my bad lol, I'll check with Esfand and see what see if I can get that :)

**Comment by Sdyess** [comment]
Wasn't a viable idea, closing the enhancement.
