### ISSUE TITLE
Show latest youtube video in Popup

### ISSUE THREAD

**Issue by Sdyess** [Sdyess/EsfandUpdates#9]
Esfand wants the latest youtube video in the popup.
Might require some level of redesign to keep the popup from being absolutely massive.

**Comment by hkmcoding** [comment]
![image](https://user-images.githubusercontent.com/30579227/152606124-ca3e9b93-fef7-42e1-8047-7d1350417ac1.png)

I have it working without thumbnails for now. Styles pretty much replicate onlyfands YT section. Let me know if you want to go live with this before any potential redesign, I'll send over the PR 💯

**Comment by Sdyess** [comment]
The problem with this is that it's just really big now, do you have any ideas how we could keep it near the same size but also include YT section? I'm considering making the live section smaller or splitting the tweet in half

**Comment by hkmcoding** [comment]
I'll try and mock something up. I heard that Esfand wants the thumbnail in it too. Maybe something like a bottom nav with a dynamic panel for latest yt video, tweet, etc? Kind of similar to Bitwarden if you use it.

![image](https://user-images.githubusercontent.com/30579227/152620093-30762858-e401-4d75-8662-40af96674c98.png)

Layout would be
- Live panel
- Dynamic panel
- Bottom "nav" with YT icon, Twitter icon, etc. (can add icons as we go? it could also be a carousel/slideshow with each panel having its own CTA)

**Comment by Sdyess** [comment]
![image](https://user-images.githubusercontent.com/4682306/153381173-9cbe5491-5dfc-4634-9104-66cd3297189e.png)
This is a partial completion of the new design

**Comment by Sdyess** [comment]
Completed in 0f696a102dc10001e220306976664591c2bc126f
